### ISSUE TITLE
Kutuphane yazılımı 

### ISSUE THREAD

**Issue by alperenMert** [haticeerturk/Kutuphane-Yazilimi#1]
Merhaba, ben Fırat üniversitesi bilgisayar mühendisliği öğrencisi Alperen. Size kütüphane yazılımı hakkında bir soru sormak istiyorum acaba hazır bir veri tabanınız var mı yoksa kendimiz kurmamız mı gerekiyor veri tabanını eğer varsa bana gönderebilir misiniz teşekkürler.

**Comment by haticeerturk** [comment]
Merhaba Alperen,

Çok uzun zaman oldu bu işle uğraşalı, fakat hazır bir db bulunmamakta.
Kendin kurup kendi bilgilerin ile db yi projeyle bağlayıp çalıştırmalısın.

Kolay gelsin.

Alperen MERT <notifications@github.com>, 25 Haz 2019 Sal, 12:09 tarihinde
şunu yazdı:

**Comment by alperenMert** [comment]
Teşekkür ederim :)

25 Haz 2019 Sal 13:23 tarihinde Hatice ERTÜRK <notifications@github.com>
şunu yazdı:
